### ISSUE TITLE
UserWarning: PySoundFile failed. Trying audioread instead.

### ISSUE THREAD

**Issue by udaylunawat** [turpaultn/DCASE2019_task4#13]
Downloading real recording raises these warnings & it doesn't even downloads all the files

`/home/udaylunawat/anaconda3/envs/dcase2019/lib/python3.6/site-packages/librosa/core/audio.py:161: UserWarning: PySoundFile failed. Trying audioread instead.`

**Comment by udaylunawat** [comment]
![image](https://user-images.githubusercontent.com/24354945/72456587-f1fd3680-37ea-11ea-8136-d527a1da3737.png)
The real dataset downloads no more than 2GB of data files

**Comment by turpaultn** [comment]
I suspect a problem with the installation of soundfile in the environment.
If you use anaconda, could you try to reinstall soundfile with conda (-c conda-forge) and make sure you do not have any other versions (with pip) ?

**Comment by turpaultn** [comment]
Any update ?

**Comment by udaylunawat** [comment]
Got the dataset!!
