### ISSUE TITLE
Is this mean filter really correct?

### ISSUE THREAD

**Issue by SimZhou** [turpaultn/DCASE2019_task4#18]
https://github.com/turpaultn/DCASE2019_task4/blob/4d42e1fcc2cc0097979ac0f5935f0fd548945e0a/baseline/evaluation_measures.py#L214
In my understanding, pred_strong should be an array of 2 dims: (BatchSize, SeqLength), 
the median filter should do the median along the sequence, not the batch. 

So I guess the filter should be (1, cfg.median_window) ?

**Comment by turpaultn** [comment]
Sorry for the delay in my answer.
The array is of 2 dims: (SeqLength, NbClasses), that is why the median filter is like this :)
