### ISSUE TITLE
About train

### ISSUE THREAD

**Issue by MichelleYang2017** [turpaultn/DCASE2019_task4#5]
If I want to train  from scratch,what should the 'subpart_data' params in main.py   choose? Thank you

**Comment by MichelleYang2017** [comment]
I get it. Don't fix it,right?

**Comment by turpaultn** [comment]
Exactly, if it is None, it uses all the data. 
This parameter is just for practical purposes, you can use it to see if the training works on a subpart of the data (to not wait hours before getting an error).
